// ACTIONS APP
export const ACTION_LOADMENU = 'LOADMENU';

// ACTIONS USER
export const ACTION_CLIENTE_SET = 'CLIENTE_SET';
export const ACTION_SET_REGISTER_FULL = 'SET_REGISTER_FULL';
export const ACTION_UPDATE = 'UPDATE';

// ACTIONS CAR
export const ACTION_SHOPCAR = 'SHOPCAR';
export const ACTION_SET_DIR_SHOPCAR = 'SET_DIR_SHOPCAR';

// ACTIONS CAR
export const ACTION_DEL_SHOPCAR = 'DEL_SHOPCAR';

// UPDATE TOTALS SHOPCAR
export const UPDATE_TOTALS_SHOPCAR = 'UPDATE_TOTALS_SHOPCAR';

// ACTIONS ADDRESS
export const ACTION_ADDRESS = 'ADDRESS';

// ACTIONS SHOPCAR_COPY
export const ACTION_SHOPCAR_COPY = 'SHOPCAR_COPY';

// ACTIONS PAYMENT_RESPONSE
export const ACTION_PAYMENT_RESPONSE = 'PAYMENT_RESPONSE';

// ACTIONS CAR
export const ACTION_PAYMENT_ORDER = 'PAYMENT_ORDER';

// UPDATE BUSCADOR
export const UPDATE_BUSCADOR = 'UPDATE_BUSCADOR';

// UPDATE_MENU_MOBILE
export const UPDATE_MENU_MOBILE = 'UPDATE_MENU_MOBILE';

// UPDATE_MENU_MOBILE_SEARCH
export const UPDATE_MENU_MOBILE_SEARCH = 'UPDATE_MENU_MOBILE_SEARCH';

// SET_SEDES
export const SET_SEDES = 'SET_SEDES';

// GET_MIS_BONOS
export const GET_MIS_BONOS = 'GET_MIS_BONOS';

// GET_MIS_BONOS
export const ADD_FAVORITOS = 'FAVORITOS';

// ACTIONS APP
export const ACTION_HEADER_STATE = 'HEADER_STATE';

// ACTIONS FOR ASOCIADOS
export const ACTION_CONSULTA_STATE_ASOCIADO = 'PN_ASOCIADOS_RT_CONSULTA_STATE';
export const ACTION_DATA_ASOCIADO = 'ACTION_DATA_ASOCIADO';
export const ACTION_SET_DATA_ASOCIADO = 'ACTION_SET_DATA_ASOCIADO';
export const ACTION_GET_DATA_ASOCIADO = 'ACTION_GET_DATA_ASOCIADO';

// ACTIONS USER
export const ACTION_LOGOUT = 'LOGOUT';
export const ACTION_LOGIN = 'LOGIN';
