
export const MIM_PARAMETROS = {
  MIM_VALOR_DEVOLVER: {
    AUXILIO: 55,
    ESTADOS: '1,4,7,8'
  },
  MIM_ESTADO_REGISTRO: {
    ACTIVO: 1,
    INACTIVO: 0
  },
  MIM_ESTADO_CLIENTE: {
    INACTIVO: 1,
    ACTIVO: 2,
    PROCESO: 3,
    OBSERVACION: 4
  },
  MIM_ESTADO_COBERTURA: {
    INACTIVO: 1,
    ACTIVO: 2,
    PROCESO: 3,
    OBSERVACION: 4
  },
  MIM_ESTADO_PLAN: {
    INACTIVO: 1,
    ACTIVO: 2,
    PROCESO: 3,
    EN_ELIMINACION: 4
  },
  MIM_ESTADO_PLAN_COBERTURA: {
    INACTIVO: 1,
    ACTIVO: 2,
    PROCESO: 3,
    EN_ELIMINACION: 4
  },
  SIP_HOMOLOGACION_CATEGORIAS: {
    ACTIVO: '1',
    INACTIVO: '2'
  },
  SIP_CATEGORIA_ASOCIADO: {
    ACTIVO: true,
    INACTIVO: false
  },
  MIM_ESTADOS_SOLICITUD_EVENTO: {
    EN_PROCESO: 1,
    PAGADA: 2,
    NEGADA: 3,
    ANULADA: 4,
    SUSPENDIDA: 5
  },
  MIM_SUBESTADO: {
    PENDIENTE_CONTACTO: 'GES_PEN_CONTACTO',
    PENDIENTE_CONCEPTO: 'GES_PEN_CONCEPTO',
    NECESITA_TELECONFERENCIA_AUDITOR: 'GES_NEC_TEL_AUDITOR'
  },
  MIM_ESTADO_CIERRE: {
    ASOCIADO_ACEPTA_RAZON_NEGACION: 1,
    CONTACTO_TELEFONICO_NO_EXITOSO: 2,
    ASOCIADO_INSATISFECHO: 3,
    NOTIFADO_TAYLOR: 4,
    SIN_NOTIFICAR: 5,
  },
  MIM_VALOR_ASEGURADO: {
    VOLUNTARIO: 1,
    TOPE_DEFINIDO: 2,
    PORCENTAJE_OTRA_COBERTURA: 3,
    CUOTA_OTRAS_COBERTURAS: 4,
    VOLUNTARIO_PROMEDIO_OTRA_COBERTURA: 5,
    PROTECCION_OTRAS_COBERTURAS: 6,
    TOPE_OTRA_COBERTURA: 7
  },
  MIM_TIPO_DEDUCIBLE: {
    DINERO: 3
  },
  MIM_SUBLIMITE_COBERTURA: {
    TIPO_SUBLIMITE_PORCENTAJE: 1,
    TIPO_SUBLIMITE_DEFINIDO: 2
  },
  MIM_ENFERMEDAD_GRAVE: {
    TIPO_VALOR_PROTECCION: 1,
    TIPO_VALOR_FIJO: 2,
    TIPO_VALOR_ASEGURADO_PROTECCION: 3
  },

  MIM_TIPO_VALOR_DEVOLVER: {
    DEFINIDO: 2,
    PORCENTAJE_COBERTURA: 3
  },

  MIM_FORMA_PAGO: {
    CHEQUE: 1,
    DEPOSITOS: 2,
    DISTRIBUCION: 3
  },
  MIM_COTIZACION_TIPO_CALCULO: {
    VALOR_CUOTA: 0,
    VALOR_PROTECCION: 1,
    VALOR_CUOTA_PROTECCION: 2
  },
  MIM_TIPO_MOVIMIENTO: {
    INCREMENTO: 2,
    COTIZACION: 5
  },

  MIM_TIPO_RECONOCIDO: {
    COP: 1,
    SMMLV: 2,
    PORCENTAJE: 3 
  },

  MIM_ESTADO_COTIZACION: {
    EN_PROCESO_VENTA: 1,
    EFECTIVO: 2,
    DISPONIBLE: 3,
    NO_VIGENTE: 4
  },
  MIM_ESTADO_VENTA: {
    EN_VALIDACION: 1, // EN_PROCESO_VENTA
    APROBADA: 2, // EFECTIVO
    NEGADA: 3, // DISPONIBLE
    ANULADA: 4, // NO_VIGENTE
    SUSPENDIDA: 5
  },
  MIM_GENERO: {
    TODOS: 3,
    FEMENINO: 2,
    MASCULINO: 1
  },

  MIM_TIPO_INCREMENTO: {
    ACTIVO: 1,
    CERRADO: 2
  },

  MIM_FASE_FLUJO: {
    RADICACION: 1,
    AUDITORIA_MEDICA: 2,
    LIQUIDACION: 3,
    PAGO: 4,
    NOTIFICAR_APROBACION: 5,
    NOTIFICAR_NEGACION: 6,
    REGISTRO: 7,
    TECNICA: 8,
    ACTUARIA: 9,
    FINALIZADO: 10,
    FINANCIERA: 11,
    OFICINA_CUMPLIMIENTO: 12,
    JEFE_RIESGOS: 13,
    MESA_CONTROL: 14,
    AUDITORIA_MEDICA_INCREMENTO: 15,
    GESTION_AREA_TECNICA: 16,
    REGISTRO_INCREMENTO: 18,
    PRE_REGISTRO: 21
  },
  MIM_FASE_PROCESO: {
    PROCESO_VENTA_INCREMENTO: 'incrementos',
    PROCESO_MEDICAMENTOS: 'procesoRadicacionMedicamentos'
  },
  // LA MANERA PARA DEFINIR LOS ELEMENTOS D EESTA CONFIGURACION ES: CONCATENAR EL PROCESO, EL NOMBRE DE LA FASE
  // Y EL NOMBRE DEL CONCEPTO
  MIM_CONCEPTO_TAREA_FLUJO: {
    PROCESO_MEDICAMENTOS_REGISTRO_SOLICITUD_INFORMACION: 1,
    PROCESO_MEDICAMENTOS_RADICACION_DESFAVORABLE: 2,
    PROCESO_MEDICAMENTOS_AUDITORIA_MEDICA_FAVORABLE: 5,
    PROCESO_MEDICAMENTOS_AUDITORIA_MEDICA_DESFAVORABLE: 6,
    PROCESO_MEDICAMENTOS_AUDITORIA_MEDICA_SOLICITUD_INFORMACION: 7,
    PROCESO_MEDICAMENTOS_AUDITORIA_MEDICA_DEVOLUCION_ERROR: 8,
    PROCESO_MEDICAMENTOS_DEFINICION_FAVORABLE: 9,
    PROCESO_MEDICAMENTOS_DEFINICION_DESFAVORABLE: 10,
    PROCESO_MEDICAMENTOS_DEFINICION_SOLICITUD_INFORMACION: 11,
    PROCESO_MEDICAMENTOS_DEFINICION_DEVOLUCION_ERROR: 12,
    PROCESO_MEDICAMENTOS_PAGO_FAVORABLE: 13,
    PROCESO_MEDICAMENTOS_PAGO_DESFAVORABLE: 14,
    PROCESO_MEDICAMENTOS_PAGO_SOLICITUD_INFORMACION: 15,
    PROCESO_MEDICAMENTOS_PAGO_DEVOLUCION_ERROR: 16,
    PROCESO_VENTA_INCREMENTO_AUDITORIA_MEDICA_FAVORABLE: 21,
    PROCESO_VENTA_INCREMENTO_AUDITORIA_MEDICA_DESFAVORABLE: 22,
    PROCESO_VENTA_INCREMENTO_AUDITORIA_MEDICA_SOLICITAR_INFORMACION: 23,
    PROCESO_VENTA_INCREMENTO_AUDITORIA_MEDICA_GLOSAR: 24,
    PROCESO_VENTA_INCREMENTO_GESTION_OPERACIONES_APROBAR: 25,
    PROCESO_VENTA_INCREMENTO_GESTION_OPERACIONES_GLOSAR: 26,
    PROCESO_VENTA_INCREMENTO_OFICIAL_CUMPLIMIENTO_FAVORABLE: 17,
    PROCESO_VENTA_INCREMENTO_OFICIAL_CUMPLIMIENTO_DESFAVORABLE: 18,
    PROCESO_VENTA_INCREMENTO_JEFE_RIESGOS_FAVORABLE: 19,
    PROCESO_VENTA_INCREMENTO_JEFE_RIESGOS_DESFAVORABLE: 20,
    PROCESO_VENTA_INCREMENTO_GESTION_AREA_TECNICA_FAVORABLE: 3,
    PROCESO_VENTA_INCREMENTO_GESTION_AREA_TECNICA_DESFAVORABLE: 4,
    PROCESO_VENTA_INCREMENTO_GESTION_AREA_TECNICA_SOLICITAR_INFORMACION: 27,
    PROCESO_VENTA_INCREMENTO_GESTION_AREA_TECNICA_GLOSAR: 28
  },
  MIM_RAZON_ANULACION: {
    ERROR_USUARIO: 1,
    ATRIBUIBLE_ASOCIADO: 3
  },
  MIM_COBERTURAS: {
    MUERTE_ACCIDENTAL: 6
  },
  MIM_TIPO_VALOR_PROTECCION: {
    PORCENTAJE_COBERTURA: 1
  },
  MIM_PROCESO_AUTOMATICO: {
    JOB_GROUP: 'procesosAutomaticos'
  },
  MIM_ESTADO_PRE_VENTA: {
    DISPONIBLE: 1,
    NEGADA: 2,
    ANULADA: 3,
    COMPLETADA: 4
  },
  MIM_TIPO_VALOR_TOPE: {
    COP: 1,
    SMMLV: 2,
    INGRESO_DIARIO: 3,
    PORCENTAJE_OTRA_COBERTURA: 4
  },
  MIM_ESTADO_PERIODO: {
    ACTIVO: 1,
    INACTIVO: 2,    
    PROCESO: 3
  },
  MIM_TIPO_VALOR_RESTITUCION: {
    VITALICIA: 1,
    VIGENCIA_INDIVIDUAL: 2,
    VIGENCIA_CALENDARIO: 3
  },
  MIM_PRESENTACION_PORTAFOLIO:{
    SI_AMPARA: 1,
    VALOR_ASEGURADO: 2,
    RANGO_PORCENTAJE: 3,
    RANGO_RENTAS: 4,
    HASTA_POR: 5,
    VALOR_PERIODO: 6
  },
  MIM_TIPO_ASOCIADO: {
    RESPONSABLE_PAGO: "1",
    ASEGURADO: "2",
    ASEGURADO_NOMBRE: "Asegurado",
    RESPONSABLE_PAGO_NOMBRE : "Responsable de pago"
  },
  MIM_CANALES_VENTA:{
    BARRA_COMERCIAL: 1,
    CALL_CENTER: 2
  },
  MIM_TIPO_COTIZACION: {
    UNICA: 1,
    MULTIPLE: 2
  }
};
