/**
 * @description Configuracion de SIP_PARAMETROS_TIPO.
 * **NOTA: Este archivo se debe actualizar de manera incremental iniciando
 * con el predijo TIPO_<NOMBRE_TIPO_PARAMETRO>.
 * ** IMPORTANTE: Se debe mantener el orden de acuerdo al TIP_COD de menor a mayor.
 */
export const SIP_PARAMETROS_TIPO = {
  // TODO(alobaton): Se deben refactorizar estos parametros.
  GENERALES: {
    TIP_COD: 1,
    CODIGO: {
      DIAS_MAX_SOLICITUD_COTIZACION: 100,
      VALOR_MAX_MORA_PERMITIDA: 9,
      NUMERO_CUOTAS_AX_PERMITIDA: 101
    }
  },
  TIPOS_IDENTIFICACION: { TIP_COD: 20 },
  TIPOS_PARENTESCO: { TIP_COD: 101 },
  AUXILIO_TIPO_ACCION: { TIP_COD: 61 },
  NO_MONETARIO_TIPO_ACCION: { TIP_COD: 91 },
  CANAL_VENTA: { TIP_COD: 40 },
  PROMOTORES: { TIP_COD: 226 },
  RETENCION_EVENTO: { TIP_COD: 243 },

  /**
   * Estados en la tabla de SIP_PARAMETROS.
   */
  ESTADO_ACTIVO: 1,
  ESTADO_INACTIVO: 2,
  /**
   * AFIRMACIONES
   * TIP_COD: 2
   */
  TIPO_AFIRMACIONES: {
    TIP_COD: 2,
    SIP_PARAMETROS: {
      SI: 1,
      NO: 2
    }
  },
  /**
   * ESTADOS PROTECCIONES
   * TIP_COD: 3
   */
  TIPO_ESTADOS_PROTECCIONES: {
    TIP_COD: 3,
    SIP_PARAMETROS: {
      ACTIVO: 1,
      INACTIVO: 2,
      INACTIVO_RETIRO: 6,
      INACTIVO_MORA: 4,
      ANULADO: 9,
      PAGADO: 5,
      ACTIVO_ESPECIAL: 8,
      SUSPENDIDO_MORA: 7,
      RETENCION: 0,
      PRE_VINCULADO: 3,
      RECESO: 12
    }
  },
  /**
   * TIPOS DE FORMAS DE PAGO AUXILIO FUNERARIO
   * TIP_COD: 80
   */
  TIPO_INDICADOR_AUX_FUNERARIO: {
    TIPO_COD: 4,
    SIP_PARAMETROS: {
      COD_AUXILIO_FUNERARIO: 84,
      ESTADO_NOVEDAD: 1,
      COD_RENUNCIA: 1
    },
    SIP_INDICADORES: {
      CREDITO_T70: 2,
      CUOTA_UNICA: 4
    },
    // TODO(hander): Esto se debe llevar a un parametro de estados de beneficiario.
    SIP_ESTADOS: {
      TIPO_BENEFICIARIO: '2',
      REPETIDO: '3',
      ACTIVO: '1',
      DES_ACTIVO: 'ACTIVO',
      DES_INACTIVO: 'INACTIVO'
    }
  },

  /**
  * ESTADOS BENEFICIARIOS
  */
  TIPO_ESTADOS_BENEFICIARIOS: {
    TIP_COD: 5,
    SIP_PARAMETROS: {
      ACTIVO: '1',
      INACTIVO: '2',
      REPETIDO: '3',
      PENDIENTE_ACTIVACION: '4',
      REPETIDO_FALLECIDO: '5'
    }
  },
  /**
   * CAUSAS DE PREEXISTENCIAS
   * TIP_COD: 8
   */
  TIPO_CAUSAS_PREEXISTENCIAS: {
    TIP_COD: 8
  },
  /**
   * ESTADOS CUOTAS FACTURACION
   * TIP_COD: 12
   */
  TIPOS_ESTADOS_CUOTAS_FACTURACION: {
    TIP_COD: 12
  },
  /**
   * FORMAS DE PAGO
   * TIP_COD: 31
   */
  TIPO_FORMAS_PAGO: {
    TIP_COD: 31,
    SIP_PARAMETROS: {
      GIRO: 1,
      DEPOSITOS: 2,
      DISTRIBUIDA: 4,
      DISTRIBUIDA_RENTAS: 6
    }
  },
  /**
   * ESTADOS DE PREEXISTENCIAS
   * TIP_COD: 33
   */
  TIPO_ESTADOS_PREEXISTENCIAS: {
    TIP_COD: 33,
    SIP_PARAMETROS: {
      ACTIVA: 1,
      INACTIVA: 2
    }
  },
  /**
   * ESTADOS RECLAMACIONES
   * TIP_COD: 44
   */
  TIPO_ESTADOS_RECLAMACIONES: {
    TIP_COD: 44,
    SIP_PARAMETROS: {
      OBJETADA: 16,
      ANULADA: 2,
      TERMINADA_OBJETADA: 21,
      NEGADA: 14
    }
  },
  /**
   * INDICADOR FECHA NACIMIENTO
   * TIP_COD: 79
   */
  TIPO_INDICADOR_FECHA_NACIMIENTO: {
    TIP_COD: 79,
    SIP_PARAMETROS: {
      FEC_NAC_CORRECTA_VALIDA: 1
    }
  },
  /**
   * SUBSERIE INDICADOR FECHA NACIMIENTO
   * TIP_COD: 80
   */
  TIPO_SUBSERIE_INDICADOR_FECHA_NACIMIENTO: {
    TIP_COD: 80
  },
  /**
 * ESTADOS DE REGISTRO DEL BENEFICIARIO
 */
  TIPO_ESTADOS_REGISTRO_DEL_BENEFICIARIOS: {
    TIP_COD: 93,
    SIP_PARAMETROS: {
      ACTIVO: '1',
      INACTIVO: '2',
      PRE_VINCULADO: '3',
      PAGADO: '5',
      RETIRADO: '6',
      ANULADO: '9'

    }
  },
  /**
   * CORTES DE FACTURACION
   * TIP_COD: 117
   */
  TIPO_CORTES_FACTURACION: {
    TIP_COD: 117
  },
  /**
   * TIPOS DE CONTRATOS AUXILIO DESEMPLEO
   * TIP_COD: 138
   */
  TIPO_CONTRATOS_AUXILIO_DESEMPLEO: {
    TIP_COD: 138
  },
  /**
  * TIPOS DE RECONOCIMIENTOS
  * TIP_COD: 349
  */
  TIPO_RECONOCIMIENTOS: {
    TIP_COD: 349,
    SIP_PARAMRTROS: {
      CANTIDAD_RENTAS: 2
    }
  },
  /**
   * ESTADOS DE DIAGNOSTICOS
   */
  TIPO_ESTADOS_DIAGNOSTICOS: {
    SIP_PARAMETROS: {
      ACTIVO: 1,
      INACTIVO: 0
    }
  },
  /**
   * OFICINAS
   */
  OFICINAS_EXCLUIDAS: {
    PAGO_POR_GIRO: 225,
    VALOR_MINIMO: 367
  },

  RECLAMO_POR: {
    ASOCIADO: 3,
    BENEFICIARIO: 1
  },
  /**
   * CODRET SIPINTLIQ
   * TIP_COD: 384
   */
  TIPO_CODRET_SIPINTLIQ: {
    TIP_COD: 384,
    SIP_PARAMETROS: {
      APLICADA: 1
    }
  },
  /**
   * CODRET SIPINTLIQ
   * TIP_COD: 402
   */
  USUARIO_SISTEMA: {
    TIP_COD: 402
  },
  /**
   * CODEMP
   */
  TIPO_CODEMP: {
    TIP_COD: 403,
    SIP_PARAMETROS: {
      CODEMP: 67890
    }
  },

  /**
   * MIM_ESTADOS_PROTECCION
   */
  ESTADOS_PROTECCION: {
    PRE_VINCULACION: 3
  },

  BASE_RETENCION_FUENTE: {
    TIP_COD: 1,
    SIP_PARAMETROS: {
      CUANTIA_DIAN: 14
    }
  },

  TIPO_ESTADOS_ASOCIADO: {
    SUSPENDIDO_NORMAL: 20,
    INACTIVO: 9
  },
  TIPO_ESTADOS_RENTAS: {
    TIP_COD: 145,
    SIP_PARAMETROS: {
      PENDIENTE: 1,
      PAGADA: 2,
      ANULADA: 3
    }
  },
  TIPO_PREGUNTAS: {
    SIP_PARAMETROS: {
      SIPAS: 2,
      SICO: 1
    }
  },
  SIP_PREGUNTAS: {
    PREGUNTA_1: 1,
    PREGUNTA_2: 2,
    PREGUNTA_3: 3,
    PREGUNTA_4: 4,
    PREGUNTA_5: 5,
    PREGUNTA_6: 6,
    PREGUNTA_7: 7
  },

  CONFIGURACION_PROCESO_VENTA_INCREMENTO: {
    TIP_COD: 420
  },

  SIP_ESTADO_FACTURA: {
    PENDIETE_PAGO: "1"
  }
};
