// Codigos menus
export class CodigosMenu {
  // Consultas
  static CONSULTAS = 'MM_CONSULTA';
  static CONSULTAS_ASOCIADOS = 'MM_FLOTANTE_CONSULTA_ASOCIADO';
  static CONSULTAS_ASOCIADOS_DATOS_BASICOS = 'MM_CONSUL_ASOC_DATOS_BASICO';
  static CONSULTAS_ASOCIADOS_BENEFICIARIOS = 'MM_CONSUL_ASOC_BENEFICIARIOS';
  static CONSULTAS_ASOCIADOS_PROTECCIONES = 'MM_CONSUL_ASOC_PROTECCIONES';
  static CONSULTAS_ASOCIADOS_PROTECCIONES_PORTAFOLIO = 'MM_CONSUL_ASOC_PROTECCIONES_PORTAFOLIO';
  static CONSULTAS_ASOCIADOS_PROTECCIONES_PORTAFOLIO_ACCION = 'MM_CONSUL_ASOC_PRO_PORT_ACCION';
  static CONSULTAS_ASOCIADOS_PROTECCIONES_PORTAFOLIO_ACCION_DESCARGAR = 'MM_CONSUL_ASOC_PRO_PORT_ACCION_DESCARGAR';
  static CONSULTAS_ASOCIADOS_PROTECCIONES_PORTAFOLIO_ACCION_BITACORA = 'MM_CONSUL_ASOC_PRO_PORT_ACCION_BITACORA';
  static CONSULTAS_ASOCIADOS_PROTECCIONES_PORTAFOLIO_MOVIMIENTOS = 'MM_CONSUL_ASOC_PRO_PORT_MOVIMIENTOS';
  static CONSULTAS_ASOCIADOS_PROTECCIONES_PORTAFOLIO_MOVIMIENTOS_COTIZACION = 'MM_CONSUL_ASOC_PRO_PORT_COTIZACION';
  static CONSULTAS_ASOCIADOS_PROTECCIONES_PORTAFOLIO_MOVIMIENTOS_INCREMENTO = 'MM_CONSUL_ASOC_PRO_PORT_INCREMENTO';
  static CONSULTAS_ASOCIADOS_FACTURACION = 'MM_CONSUL_ASOC_FACT';
  static CONSULTAS_ASOCIADOS_FACTURACION_CAPITAL_PAGADO = 'MM_CONSUL_ASOC_FACT_CAPITAL_PAGADO';
  static CONSULTAS_ASOCIADOS_FACTURACION_CUENTAS_CONTABLES = 'MM_CONSUL_ASOC_FACT_CUENTAS_CONTABLES';
  static CONSULTAS_ASOCIADOS_FACTURACION_MULTIACTIVA = 'MM_CONSUL_ASOC_FACT_MULTIACTIVA';
  static CONSULTAS_ASOCIADOS_FACTURACION_RECAUDOS = 'MM_CONSUL_ASOC_FACT_RECAUDOS';
  static CONSULTAS_ASOCIADOS_FACTURACION_SOLIDARIDAD = 'MM_CONSUL_ASOC_FACT_SOLIDARIDAD';
  static CONSULTAS_ASOCIADOS_PREEXISTENCIAS = 'MM_CONSUL_ASOC_PREEXISTENCIAS';
  static CONSULTAS_ASOCIADOS_GENERAL = 'MM_CONSUL_ASOC_GENERAL';
  static CONSULTAS_ASOCIADOS_GENERAL_AUX_FUN = 'MM_CONSUL_ASOC_GENERAL_IND_AUXFUN';
  static CONSULTAS_ASOCIADOS_GENERAL_IND_FEC_NAC = 'MM_CONSUL_ASOC_GENERAL_IND_FECH_NACIMI';
  static CONSULTAS_LIQUIDACIONES = 'MM_CONSUL_LIQUIDACIONES';
  static CONSULTAS_RECLAMACIONES = 'MM_CONSUL_RECLAMACIONES';
  static CONSULTAS_RECLAMACIONES_ACCION_BITACORA = 'MM_CONSUL_RECLAMACIONES_ACCION_BITACORA';
  static CONSULTAS_RECLAMACIONES_ACCION_RENTAS = 'MM_CONSUL_RECLAMACIONES_ACCION_RENTAS';
  static CONSULTAS_PAGOS = 'MM_CONSUL_PAGOS';
  static CONSULTAS_LOG_TRANSACCIONAL = 'MM_CONSUL_LOGTRANSACC';
  static CONSULTAS_EVENTOS_CONSULTA_SOLICITUD_ACTIVAR = 'MM_ACTIVAR_SOLICITUD_EVENTO';
  static CONSULTAS_EVENTOS_CONSULTA_SOLICITUD_ANULAR = 'MM_CONSUL_RECLAMACIONES_ACCION_ANULAR';
  static CONSULTAS_RECLAMACIONES_ACCION_OBSERVACIONES = 'MM_CONSUL_RECLAMACIONES_ACCION_OBSERVACION'

  // Administracion
  static ADMINISTRACION = 'MM_ADMINISTRACION';
  static ADMINISTRACION_ASOCIADOS_VIP = 'MM_ADMIN_ASOCIADOS_VIP';
  static ADMINISTRACION_SEGURIDAD = 'MM_ADMIN_SEGURIDAD';
  static MM_ADMIN_CONFIG_OPERACIONES = 'MM_ADMIN_CONFIG_OPERACIONES';
  static MM_ADMIN_CONFIG_ASIGDIARIA = 'MM_ADMIN_CONFIG_ASIGDIARIA';

  // Simulaciones
  static SIMULACIONES = 'MM_SIMULACIONES';
  static SIMULACIONES_VALOR_DEVOLVER = 'MM_SIMUL_VALORESDEVOLVER';
  static SIMULACIONES_VALOR_DEVOLVER_CANCELADA = 'MM_SIMULACIONES_VALOR_DEVOLVER_CANCELADA';
}
