export enum CatLinkEnum {
    FAMILIAR_ASOCIADO = 126,
    FAMILIAR_ASOCIADO_FALLECIDO = 888,
    ESTUDIANTE = 33,
    EGRESADO_RECIEN_GRADUADO = 35,
    PROFESIONAL = 885,
    TECNICO_Y_TECNOLOGOS = 886,
    MAYORES_DE_60_ANIOS = 887,
    ASESOR_COMERCIAL = 889,
    EMPLEADO_NO_PROFESIONAL= 34,
}